# Generated by Django 2.2.4 on 2019-09-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hiring_date', models.DateTimeField(verbose_name='date published')),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField(max_length=200)),
                ('cell_phone', models.IntegerField(max_length=200)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
            },
        ),
    ]
