# Generated by Django 2.2.4 on 2019-09-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='manager',
            new_name='parent',
        ),
    ]
