# Generated by Django 2.2.4 on 2019-09-01 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cell_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hiring_date',
            field=models.DateTimeField(verbose_name='hiring date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
